version: '3.9'

services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - '8080:8080'
    restart: unless-stopped
    volumes:
      - ./openapi.yaml:/app/openapi.yaml:ro

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - '8081:8080'
    environment:
      SWAGGER_JSON: /spec/openapi.yaml
    volumes:
      - ./openapi.yaml:/spec/openapi.yaml:ro
